config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :user do
    get '/edit', to: 'profile#edit'
    patch '/', to: 'profile#update'
    get '/', to: 'dashboard#index'

    resources :trips, only: [:index, :new, :create, :show, :edit]
    resources :trip_events, only: [ :new, :update]

    namespace :trips do
      namespace :upcoming do
        resources :trips, only: [:index]
      end
      namespace :past do
        resources :trips, only: [:index, :show]
      end
    end
  end

  namespace :visitor do
    resources :trips, only: [:new, :create]
  end

  post '/email', to: "email#create"
  get '/login', to: 'login#index'
  delete "/logout", to: "sessions#destroy"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :date, presence: true

  has_many :trip_events, dependent: :destroy
  has_many :trips, through: :trip_events
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :trip_events, dependent: :destroy
  has_many :events, through: :trip_events
  belongs_to :user

  def populate(genres, trip_params)
    event_list = EventService.new.events_by_genres(genres, trip_params)
    event_list.each do |event|
      events << Event.create(event)
    end
  end

  def self.past_trips
    where('end_date < ?', 1.day.ago)
  end

  def self.upcoming_trips
    where('end_date > ?', 1.day.ago)
  end
end

app/models/trip_event.rb
class TripEvent < ApplicationRecord
  belongs_to :trip
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true
  validates :password_digest, presence: true
  validates :name, presence: true
  validates :email, presence: true

  has_many :trips, dependent: :destroy

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.user_name ||= auth.info.name
      user.email = auth.info.email
      user.password_digest = SecureRandom.hex
      unless user.name
        user.name = auth.info.name
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :require_current_user

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def require_current_user
    render file: '/public/404' unless current_user
  end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def create
    recipients_email = params[:recipients_email]
    email_info = { user: current_user }
    begin
      TripMailer.send_email(email_info, recipients_email).deliver_now
      flash[:notice] = 'Your email was successfully sent'
    rescue StandardError
      flash[:message] = errors.message
    end
    redirect_to user_path
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to '/user'
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'You have successfully logged out!'
    redirect_to '/'
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :require_current_user

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < User::BaseController
  def index
    @user = current_user
  end
end

app/controllers/user/profile_controller.rb
class User::ProfileController < User::BaseController
  def edit
    @user = current_user
  end

  def update
    begin
      current_user.update!(user_params)
      redirect_to user_path
    rescue ActiveRecord::RecordInvalid
      flash[:error] = errors.messages
      render edit
    end
  end
end

app/controllers/user/trip_events_controller.rb
class User::TripEventsController < User::BaseController
  def new
    params[:genres]
    params[:trip_id]
  end

  def update
    trip_event = TripEvent.find(params[:id])
    old_event = Event.find(trip_event.event_id)
    new_event = EventService.new.event_by_genre(old_event.genre)
    old_event.update(new_event.params)

    redirect_to edit_user_trip_path(trip_event.trip)
  end
end

app/controllers/user/trips/past/trips_controller.rb
class User::Trips::Past::TripsController < User::BaseController
  def index
    @trips = Trip.past_trips
  end
end

app/controllers/user/trips/upcoming/trips_controller.rb
class User::Trips::Upcoming::TripsController < User::BaseController
  def index
    @trips = Trip.upcoming_trips
  end
end

app/controllers/user/trips_controller.rb
class User::TripsController < User::BaseController
  def index; end

  def new; end

  def create
    begin
      trip = current_user.trips.create!(trip_params)
      trip.populate(selected_genres, trip_params)
      redirect_to edit_user_trip_path(trip)
    rescue ActiveRecord::RecordInvalid
      flash[:error] = errors.messages
      render new
    end
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  private

  def trip_params
    params.permit(:city, :state, :start_date, :end_date)
  end

  def genre_params
    params.permit(:indian, :mexican, :pizza, :italian, :american, :music,
                  :sports, :theater, :amusement_parks, :museums, :zoo)
  end

  def selected_genres
    genre_params.select { |_, value| value == '1' }.keys
  end

  def attraction_params
    params.permit(:music, :sports, :theater, :amusement_parks, :museums, :zoo)
  end
end

app/controllers/visitor/base_controller.rb
class Visitor::BaseController < ApplicationController
end

app/controllers/visitor/trips_controller.rb
class Visitor::TripsController < Visitor::BaseController
  def create
    redirect_to '/visitor/trips/new'
    flash[:notice] = 'You must sign in to create a trip'
  end

  def new; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThoughtTraveler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/5716af9226.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header id="header" class="fixed-top">
    <div class="container d-flex">

      <h1 class="logo mr-auto"><a href='/'><span>Thoughtful</span>Traveler</a></h1>

      <nav class="nav-menu d-none d-lg-block">
        <aa><%= "Logged in as #{current_user.name}" if current_user %></aa>
        <ul>
            <%= link_to "Home", "/user" if current_user %>
            <%= link_to "Sign In", "/login" unless current_user %>
            <%= link_to "Logout", "/logout", method: :delete if current_user %>
        </ul>
        <div class="flash">
        <% flash.each do |name, msg| %>
        <div class= "<%=name%>-flash">
          <p><%= msg %></p>
        </div>
        </div>
      <% end %>
      </nav>
    </div>
  </header>

  <%= yield %>
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h8>USEFUL LINKS</h8>
            <ul><br>
              <li><i class="bx bx-chevron-right"></i> <a href="/user">Profile</a></li>
            </ul>
          </div>

          <div class="col-lg-5 col-md-6 footer-links">
            <a style= padding-left:80px><h8>DEV TEAM</h8></a><br><br>
            Tyler Tomlinson
            <a style= padding-left:49px href="https://github.com/tylertomlinson"><i class="fab fa-github fa-lg white-text mr-md-6 mr-5 fa-2x" aria-hidden="true"></i></a>
            <a style= padding-left:25px href="https://www.linkedin.com/in/tylerwtomlinson/"><i class="fab fa-linkedin-in fa-lg white-text mr-md-6 mr-5 fa-2x"></i></a><br><br>
            Brian Greeson
            <a style= padding-left:55px href="https://github.com/brian-greeson"><i class="fab fa-github fa-lg white-text mr-md-6 mr-5 fa-2x" aria-hidden="true"></i></a>
            <a style= padding-left:25px href="https://www.linkedin.com/in/briangreeson/"><i class="fab fa-linkedin-in fa-lg white-text mr-md-6 mr-5 fa-2x"></i></a><br><br>
            Michael Alex Lynch
            <a style= padding-left:23px href="https://github.com/mlynch5187"><i class="fab fa-github fa-lg white-text mr-md-6 mr-5 fa-2x" aria-hidden="true"></i></a>
            <a style= padding-left:25px href="https://www.linkedin.com/in/michaelalexlynch/"><i class="fab fa-linkedin-in fa-lg white-text mr-md-6 mr-5 fa-2x"></i></a><br><br>
            Jesse Gietzen
            <a style= padding-left:52px href="https://github.com/elguapogordo"><i class="fab fa-github fa-lg white-text mr-md-6 mr-5 fa-2x" aria-hidden="true"></i></a>
            <a style= padding-left:25px href="https://www.linkedin.com/in/jesse-gietzen-2w0x1/"><i class="fab fa-linkedin-in fa-lg white-text mr-md-6 mr-5 fa-2x"></i></a>
          </div>
        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">
      <div class="mr-md-auto text-center text-md-left">
        <div class="copyright">
          &copy; Copyright <strong><span></span></strong>. All Rights Reserved
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/login/index.html.erb
<div class ='google-button'>
  <a class="btn btn-primary" href="/auth/google_oauth2" role="button" style="text-transform:none">
    <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
    Login with Google
  </a>
</div>

app/views/user/dashboard/index.html.erb
<div class="container1">
  <h2 class= "carousel-header">Plan Your Next Trip</h2>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators --
    <!--
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol> -->

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img id='pics-car' src="https://i.imgur.com/c2LuljB.jpg" alt="New York" >
      </div>

      <div class="item">
        <img id='pics-car' src="https://i.imgur.com/00xPBcb.jpg" alt="Dubai">
      </div>

      <div class="item">
        <img id='pics-car' src="https://i.imgur.com/v1vp7YX.jpg" alt="Chicago">
      </div>

      <div class="item">
        <img id='pics-car' src="https://i.imgur.com/NVYrNcW.jpg" alt="Bean" >
      </div>

      <div class="item">
        <img id='pics-car' src="https://imgur.com/zMDRw44.jpg" alt="Atlantis" >
      </div>

      <div class="item">
        <img id='pics-car' src="https://imgur.com/LUtCavT.jpg" alt="Paris">
      </div>
    </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class='profile-links'>
  <%= link_to "Edit Profile", user_edit_path, class:"btn btn-primary" %>

  <%= link_to "New Trip", new_user_trip_path, class:"btn btn-primary" %>

  <% if @user.trips.upcoming_trips != [] %>
    <%= link_to "Upcoming Trips", user_trips_upcoming_trips_path, class:"btn btn-primary" %>
  <% end %>

  <% if @user.trips.past_trips.exists? %>
    <%= link_to "Past Trips", user_trips_past_trips_path, class:"btn btn-primary" %>
  <% end %>
</div>

app/views/user/profile/edit.html.erb
<div class="profile-edit">
<div class="edit-text">
<h1>Edit User Details</h1>
<%= form_with model: @user do |form| %>
<h4>Name:</h4>
  <%= form.text_field :name %><br><br>
  <%= form.submit class:"btn btn-primary btn-sm" %>
<% end %>
</div>
</div>

app/views/user/trips/edit.html.erb
<h1>Event Confirmation</h1>
<section class='event-list'>
  <% @trip.trip_events.each do |trip_event| %>
  <article id="event-<%= trip_event.event_id %>">
    <h3 id="event-<%= trip_event.event_id %>-name"><%= trip_event.event.name %></h3>
    <div id="event-<%= trip_event.event_id %>-genre"><%= trip_event.event.genre %></div>
    <%= button_to 'Pick Another',  user_trip_event_path(trip_event), method: :patch %>
  </article>
  <% end %>
</section>
<%= button_to 'Confirm Trip',  user_trip_path(@trip), method: :get %>

app/views/user/trips/new.html.erb
<h1 class="text-center1">Trip Preferences</h1>

<%= form_with model: @trip, url: user_trips_path do |form| %>
  <%= form.label :city %>
  <%= form.text_field :city %>
  <br>
  <%= form.label :state %>
  <%= form.text_field :state %>
  <br>
  <%= form.label :start_date %>
  <%= form.date_field :start_date %>
  <br>
  <%= form.label :end_date %>
  <%= form.date_field :end_date %>
  <section class="cuisine_options">
    <h1 class="text-center1">Cuisine Options</h1>
    <%= form.check_box "indian" %>
    <%= form.label "Indian" %>
    <%= form.check_box "mexican" %>
    <%= form.label "Mexican" %>
    <%= form.check_box "pizza" %>
    <%= form.label "Pizza" %>
    <br>
    <%= form.check_box "italian" %>
    <%= form.label "Italian" %>
    <%= form.check_box "chinese" %>
    <%= form.label "Chinese" %>
    <%= form.check_box "american" %>
    <%= form.label "American" %>
  </section>
  <section class="attraction_options">
    <h1 class="text-center1">Attraction Options</h1>
    <%= form.check_box "music" %>
    <%= form.label "Music" %>
    <%= form.check_box "sports" %>
    <%= form.label "Sports" %>
    <%= form.check_box "art" %>
    <%= form.label "Arts and Theater" %>
    <br>
    <%= form.check_box "amusement park" %>
    <%= form.label "Amusement Parks" %>
    <%= form.check_box "Museum" %>
    <%= form.label "Museums" %>
    <%= form.check_box "Zoo" %>
    <%= form.label "Zoo" %>
  </section>

  <%= form.submit "Create My Trip", class: "btn btn-default btn-primary" %>
<% end %>

app/views/user/trips/past/trips/index.html.erb
<h1> Past Trips </h1>

  <% @trips.each do |trip| %>
    <%= button_to "Trip to #{trip.location}", "/user/trips/#{trip.id}", method: :get %>
  <% end %>

app/views/user/trips/show.html.erb
<h1>My Trip To: <%= @trip.location %></h1>

<% @trip.events.each do |event| %>
  <h3>Event: <%= event.name %></h3></br>
<% end %>

<html>
  <head>
    <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="floating-panel">
      <button id="drop" onclick="drop()">Drop Markers</button>
    </div>
    <div id="map"></div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCTwvaJWTBV6P0rdM98__jCC0BZ7lF6o-Q&callback=initMap"
    async defer></script>
  </body>
</html>

<div class="form-wrapper">
  <%= form_tag '/email', method: :post do %>
    <div class="form-group">
      <div class="col-sm-3 my-1">
       <%= text_field_tag :recipients_email, nil, class:"form-control", id:"inlineFormInputName", placeholder: "Recipients email" %>
      </div>
    </div>
    <div class="col-auto my-1">
      <%= submit_tag "Send", class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/user/trips/upcoming/trips/index.html.erb
<h1> Upcoming Trips </h1>

  <% @trips.each do |trip| %>
    <%= button_to "Trip to #{trip.location}", "/user/trips/#{trip.id}", method: :get %>
  <% end %>

app/views/visitor/trips/new.html.erb
<h1 class="text-center1">Trip Preferences</h1>

<%= form_with model: @trip, url: visitor_trips_path do |form| %>
  <%= form.label :location %>
  <%= form.text_field :location %>
  <br>
  <%= form.label :start_date %>
  <%= form.date_field :start_date %>
  <br>
  <%= form.label :end_date %>
  <%= form.date_field :end_date %>
  <section class="cuisine_options">
    <h1 class="text-center1">Cuisine Options</h1>
    <%= form.check_box "indian" %>
    <%= form.label "Indian" %>
    <%= form.check_box "mexican" %>
    <%= form.label "Mexican" %>
    <%= form.check_box "pizza" %>
    <%= form.label "Pizza" %>
    <br>
    <%= form.check_box "italian" %>
    <%= form.label "Italian" %>
    <%= form.check_box "chinese" %>
    <%= form.label "Chinese" %>
    <%= form.check_box "american" %>
    <%= form.label "American" %>
  </section>
  <section class="attraction_options">
    <h1 class="text-center1">Attraction Options</h1>
    <%= form.check_box "music" %>
    <%= form.label "Music" %>
    <%= form.check_box "sports" %>
    <%= form.label "Sports" %>
    <%= form.check_box "theater" %>
    <%= form.label "Theater" %>
    <br>
    <%= form.check_box "amusement_parks" %>
    <%= form.label "Amusement Parks" %>
    <%= form.check_box "museums" %>
    <%= form.label "Museums" %>
    <%= form.check_box "zoo" %>
    <%= form.label "Zoo" %>
  </section>

  <%= form.submit "Create My Trip", class: "btn btn-default btn-primary" %>
<% end %>

app/views/welcome/index.html.erb
<section id="hero">
  <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

    <div class="carousel-inner" role="listbox">

      <div class="carousel-item active">
        <div class="carousel-container">
          <div class="carousel-content animated fadeInUp">
            <div class="text-center1">Your dream vacation is just a few clicks away!</div>
            <p></p>
            <% if current_user %>
            <div class="text-center"><a href="user/trips/new" class="btn-get-started">Create Trip</a></div>
            <% else %>
            <div class="text-center"><a href="visitor/trips/new" class="btn-get-started">Create Trip</a></div>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</section>